- app/src/views/ResultPage.vue
#9 Implemented result page layout.
> #9 map is shown first

- app/src/views/About.vue
Close https://github.com/hochschule-darmstadt/einander-helfen/issues/46
> Draft for about page

- app/src/components/ui/SearchBar.vue
Tiny changes no need for a huge review 🤷‍♂️ 
Close #48
> Fix missing cursor + floating label

- app/src/components/layout/Toolbar.vue
- app/src/views/Home.vue
Compare Before After:
Close #56
> Fix overlapping issue

- app/src/utils/services/DataService.ts
The geoquery is now AND connected with the search for terms.
The results are now ordered by range to the given location
should fix https://github.com/hochschule-darmstadt/einander-helfen/issues/45
> Fix geoquery

- app/src/views/ResultPage.vue
This should do the trick.
On the resultpage we now monitor the posts for emtpy values.
If we did a search with location and radius value we will increase the radius incrementel to the next bigger value and try to find results with these params.
> Increase search range when no posts are being found #43

- app/src/views/ResultPage.vue
fixed #39 
@see https://github.com/hochschule-darmstadt/einander-helfen/issues/39#issuecomment-648337843
> Added slight blue background for selected post

- app/public/index.html
- app/src/components/layout/Toolbar.vue
- app/src/views/About.vue
> Change domainName usage from .de to .org

- app/src/store/store.ts
- app/src/store/types.ts
- app/src/utils/services/DataService.ts
- app/src/views/ResultPage.vue
\+ Added PaginatedResponse Interface to DataService Responses
\+ Extended store to store all parameters needed for chunk loading
\+ Implemented server side pagination as dynamic chunk loading via 'page' parameter
\+ Added navigation to page of selected post (for when post is being opened via map)
\* renamed visiblePages => postsOnCurrentPage as a more concise name
\* removed unused imports
Please have a look if this solution is understandable.
> Adds chunk based serverside pagination

- app/src/store/store.ts
- app/src/views/Home.vue
* fixed search logic bug on home
> * now clears store on home created lifecycle hook

- app/src/views/Imprint.vue
Added all authors of issue #95 and updated design for #100.
> #95 Added authors to imprint

- app/src/views/Imprint.vue
Added position, creator, source and license of the einander-helfen.org logo to the imprint.
> #80 Added logo owner to imprint

- app/src/components/layout/Toolbar.vue
Pretty small, no review needed i guess.
Close #59
> Adjust header size to searchbarsize, Logo visible in full height

- app/src/views/Home.vue
> Swap labels

- app/src/components/ui/Radius.vue
- app/src/views/ResultPage.vue
+ Added message for empty resultset
+ Added message for when the radius has been extended
> Added message for empty resultset

- app/src/components/layout/Header.vue
- app/src/store/store.ts
> Restart search on page 1

- app/package.json
- app/public/index.html
- app/src/views/ResultPage.vue
Please test this on your mobile device and tell me how buggy it is.
> Added gesture handling to leaflet map

- app/src/components/layout/Header.vue
- app/src/views/ResultPage.vue
> Deselect current post when query changed

- app/src/views/ResultPage.vue
> Replace popup with tooltip for markers on map

- app/src/store/LocationSearch/actions.ts
- app/src/store/LocationSearch/index.ts
- app/src/store/LocationSearch/mutations.ts
- app/src/store/LocationSearch/types.ts
- app/src/store/store.ts
- app/src/utils/services/DataService.ts
- app/src/views/ResultPage.vue
+ When extending the radius don't change the users selection of radius
+ Display message for radius extension in ResultList
+ Display distance of post from selected location 
Fixes #133, #43 (again!)
> Display distance in post, don't change user radius selection

- app/src/components/ui/LocationSearchBar.vue
- app/src/utils/services/LocationService.ts
- app/src/views/Home.vue
> #64 Updated empty query and label

- app/src/components/ui/LocationSearchBar.vue
- app/src/components/ui/Radius.vue
- app/src/components/ui/SearchBar.vue
- app/src/views/Home.vue
+ Added enter event to input events
+ Added handlers to start search on homepage after second enter event
fixes #131
> Searching with 'Enter' on homepage

- app/src/views/Privacy.vue
> removed google maps from privacy page

- .github/workflows/deployProduction.yml
- app/src/store/store.ts
- app/src/views/ResultPage.vue
* Fixed fulltext-search
* Fixed linking to posts
* Removed google maps info from pricacy policy (we use OSM not Gmaps)
* Fixed spacing on resultPage details
> Last fixes before going live

- app/src/views/Imprint.vue
> * fixed whitespace bug

- etl/data_extraction/scraper/gutetat_berlin.py
This is a hotfix for the data upload process. If lat or long is None, it fails.
> Lat and long are not allowed to be None

- etl/upload_to_elasticsearch/elastic.py
> Moved index handling to the beginning

- app/src/styles/containerwithcontent.css
- app/src/views/About.vue
- app/src/views/Imprint.vue
- app/src/views/Privacy.vue
> #193 pages has the same margin as resultpage and home now

- etl/data_extraction/scraper/gutetat_berlin.py
- etl/data_extraction/scraper/gutetat_hamburg.py
- etl/data_extraction/scraper/gutetat_munich.py
- etl/main.py
To test this, temporarily remove the file ehrenamt_hessen.py from data_extraction/scraper and execute the following commands:
```
$ cd <git-repo>/etl
$ python main.py
```
Closes #202
> 202/Scraper for GuteTat Hamburg and Munich

- etl/data_extraction/scraper/ehrenamt_hessen.py
- etl/data_extraction/scraper/gutetat_berlin.py
> #208 added 'country' to post_struct['location']

- etl/data_enhancement/domain/default.py
- etl/data_extraction/Scraper.py
- etl/data_extraction/scrape_data.py
- etl/main.py
- etl/shared/utils.py
[Comment which shows the improvements](https://github.com/hochschule-darmstadt/einander-helfen/issues/205#issuecomment-738732982)
This output can be reproduced with the following commands:
```
$ cd <git-repo>/etl
$ /usr/bin/time -v python main.py
(This will take nearly 3 hours)
```
Closes #205
> #205 improved memory usage

- etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
- etl/main.py
> 213/local storage 'geocoder lat lon.csv' is not being created

- etl/docker-compose.yml
The staging server is currently running on this branch with this docker-compose. It already survived a reboot :).
I only added the `restart: always` to the existing docker-compose.
> #228 Added restart:always to the docker-compose

- etl/data_extraction/scraper/ein_jahr_freiwillig.py
- etl/data_extraction/scraper/weltwaerts.py
> #245 changed source URL

- etl/README.md
> #265 Updated README of etl

- app/src/views/ResultPage.vue
> Fixed null error on post distance function

- app/package.json
Remove dependencies that are not used in our frontend project.
This is part of splitted #289.
closes #307
> Remove unused dependencies

- app/src/App.vue
Switch from deprecated v-content to v-main
closes #310
> Use v-main

- etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
- etl/data_enhancement/enhancement_location/request_string_cleaner.py
Implemented an intelligent cleaner that removes irrelevant information based on predefined rules.
> #317/intelligent cleaning of request strings for location enhancement

- app/src/models/location.ts
- app/src/models/post.ts
- app/src/models/radius.ts
- app/src/models/tag.ts
- app/src/resources/radii/index.ts
- app/src/services/CountryService.ts
- app/src/services/DataService.ts
- app/src/services/LocationService.ts
- app/src/services/TagService.ts
Remove all double exports as they are unused
closes #295
> Remove double export

- app/src/views/About.vue
> #326 change about text

- app/package.json
- app/src/services/CountryService.ts
- app/src/services/DataService.ts
Removed the es-query-builder dependency and added the library Bodybuilder suggested from @jschurse
!close #277
> #277/replace es query builder

- etl/data_enhancement/enhance_data.py
- etl/data_enhancement/enhancement_duplicates/JsonPost.py
- etl/data_enhancement/enhancement_location/enhancement_location.py
- etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
- etl/data_extraction/Scraper.py
- etl/data_extraction/scraper/betterplace.py
- etl/data_extraction/scraper/bundesfreiwilligendienst.py
- etl/data_extraction/scraper/ehrenamt_hessen.py
- etl/data_extraction/scraper/ein_jahr_freiwillig.py
- etl/data_extraction/scraper/european_youth_portal.py
- etl/data_extraction/scraper/gutetat_berlin.py
- etl/data_extraction/scraper/weltwaerts.py
- etl/main.py
- etl/shared/utils.py
* Fixed not finished progress.
* Fixed bug that the whole backent aborts on a failed nominatim request.
> #356/revise error handling

- app/src/components/search/LocationSearchBar.vue
- app/src/components/search/SearchComponent.vue
- app/src/views/Posts.vue
> #365 fix location filter

- app/package.json
- app/src/router.ts
- app/src/services/CountryService.ts
- app/src/services/PostService.ts
- app/src/store/Posts/index.ts
- app/src/store/Search/index.ts
- app/src/store/store.ts
- app/src/views/About.vue
Set max warnings to zero, so CI fails.
Also separate lint and lint:fix, so no code is fixed on the CI
closes #352
> Let CI fail on lint warnings

- app/src/components/layout/MainHeader.vue
remove header spaces which are unnecessary
> Hotfix remove header spaces

- app/src/store/store.ts
fix radius extended bug
close #389
> #389 fix the radius extended bug

- app/src/components/search/SearchComponent.vue
set the page to the default page for any user triggered search
close #372
> #372/reset page

- app/src/components/layout/ImageCard.vue
- app/src/views/Home.vue
create ImageCard component 
close #292
> #292 seperate image cards as own component

- app/src/views/Posts.vue
> hotfix map list size bug

- app/src/views/About.vue
- etl/data_enhancement/enhance_data.py
- etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
- etl/data_extraction/scraper/sozialeinsatz.py
Implemented new scraper for [`sozialeinsatz.de`](https://www.sozialeinsatz.de/)
> #387/scraper for sozialeinsatz.de

- app/src/components/layout/MenuButton.vue
add menu icon for Organisations
> add menu icon

- app/src/App.vue
- app/src/assets/styles/style.scss
- app/src/views/Posts.vue
implement a custom scrollbar
close #399
> #399 implement custom scrollbar

- app/package.json
- app/src/main.ts
- app/src/views/Privacy.vue
Remove matomo.
Matomo should be re-added after the legal issues are sorted out.
closes #421
> Remove matomo

- app/src/components/layout/SearchHeader.vue
- app/src/components/search/SearchComponent.vue
- app/src/views/Posts.vue
implement a sticky header on the posts page
close #395
> #395/sticky header

- app/src/assets/styles/style.scss
Change background color to grey again.
> Fix background color

- app/package.json
- app/src/main.ts
- app/src/views/Privacy.vue
Legal issues are cleared up.
Changed the info-text according to our lawyer
closes #339
> Add matomo again

- app/src/components/layout/ImageCards.vue
-added border-radius to boxed images on landing page
> border-radius for boxed images on landing page

- .github/workflows/deployProduction.yml
- .github/workflows/deployStaging.yml
- .github/workflows/main.yml
This PR addresses #455 
What was changed:
- Refactored and split up workflow steps into atomic steps for better observability
- Switched from npm to yarn
- Pin node version used for builds to 14.x (same as for development)
- Added dependency caching for node_modules, which will result in faster workflow runs
- Optimized workflow triggers a bit so they only run if needed (i.e. pure BE changes will not trigger the FE workflows)
> Optimize GH actions

- app/src/components/layout/MainHeader.vue
- app/src/components/posts/PostListItem.vue
Converted h3 and p tags with span tags where necessary.
closes #460
> Remove semantic relevant tags from not main content

- app/public/index.html
> #485 added keywords to meta "description" and Meta "keywords"

- app/src/components/layout/MainHeader.vue
- app/src/components/posts/PostPagination.vue
- app/src/services/CountryService.ts
- app/src/services/PostService.ts
- app/src/store/store.ts
- app/src/views/Posts.vue
Simple refactoring: Replaced all calls of `.then` and`.catch` with async/await for better readability.
> Replace all classic usage of promises with async/await

- app/src/components/posts/MapCard.vue
> Only show permanent markertext on mobile

- etl/docker-compose.yml
Updating elasticsearch to fixed version
> log4shell hotfix

- app/src/resources/organizations/Organizations-einander-helfen.csv
> Add nebenan

- app/src/components/layout/MainHeader.vue
> Add thousands point

- app/src/components/layout/MainHeader.vue
> Add alt attributes to header icons

- app/src/views/Home.vue
#522 use longer Title. 
"Einander Helfen: das Suchportal für Freiwilligenarbeit und Ehrenamt"
> #508 use Keywords in Title

- etl/data_enhancement/enhance_data.py
- etl/data_enhancement/enhancement_continents/enhancement_continents.py
- etl/data_extraction/scrapers/de/betterplace.py
- etl/data_extraction/scrapers/de/bundesfreiwilligendienst.py
- etl/data_extraction/scrapers/de/dksb_kinderschutzbund.py
- etl/data_extraction/scrapers/de/ehrenamt_hessen.py
- etl/data_extraction/scrapers/de/ehrenamt_sachsen.py
- etl/data_extraction/scrapers/de/ein_jahr_freiwillig.py
- etl/data_extraction/scrapers/de/european_youth_portal.py
- etl/data_extraction/scrapers/de/gutetat_berlin.py
- etl/data_extraction/scrapers/de/sozialeinsatz.py
- etl/data_extraction/scrapers/de/weltwaerts.py
- etl/data_extraction/scrapers/us/volunteermatch.py
- etl/requirements.txt
Added enhancement step to enrich entries with continents.
> #285 Implemented enhance continents

- app/src/components/search/LocationSearchBar.vue
fix #452 entering numbers over numpad did not give the user suggestions.
> #452 plz over numpad not working

- app/src/views/Posts.vue
Scrolls the post-list to the selected post is in view.
closes #329
> Scroll to selected post
