hochschule-darmstadt/einander-helfen

- app/src/views/ResultPage.vue
* Renamed 'Zum Stellenangebot' => 'Zum Angebot'
* Link to source now shows 'source' field @see https://github.com/hochschule-darmstadt/einander-helfen/issues/41
* Added target="_blank" to source link
> Display 'source' as link text

- app/src/utils/services/DataService.ts
The text search now searches in the following fields:
'title', 'categories', 'task'
Is this sufficient, or shall the fields 'organization', 'location' and 'contact' also be searched?
> The search now also searches in the task field

- etl/data_extraction/Scraper.py
- etl/data_extraction/scraper/ehrenamt_hessen.py
Closes #201.
This can be tested with the following commands:
```
$ cd <git-repo>/etl
$ python (or python3)
>>> import os
>>> import sys
>>> ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
>>> os.environ['ROOT_DIR'] = ROOT_DIR
>>> sys.path.extend([f'{ROOT_DIR}/data_extraction', f'{ROOT_DIR}/shared'])
>>> from data_extraction.scraper.ehrenamt_hessen import EhrenamtHessenScraper as e
>>> a = e('ehrenamt_hessen')
>>> a.crawl('https://www.ehrenamtssuche-hessen.de/index.cfm?searchTab=job_entry_detail&jobEntryId=121912&searchLocationId=0&searchDistance=0&searchSectorIds=&searchSearchterm=&backLink=%3Fparam%26searchTab%3Dentries%26countyId%3D24%26locationId%3D424', 1)
(this added a new post to the file <git-repo>/etl/data_enhancement/data/ehrenamt_hessen.json)
>>> …
```
> Implemented check, if a post is volunteering work

- app/src/views/About.vue
- etl/data_enhancement/enhance_data.py
- etl/data_extraction/Scraper.py
- etl/data_extraction/scraper/ein-jahr-freiwillig.py
- etl/data_extraction/scraper/ein_jahr_freiwillig.py
Crawler implementation for ein-jahr-freiwillig.de
Can be tested with the following commands:
```
$ cd etl
$ python (or python3)
>>> from data_extraction.scraper.ein_jahr_freiwillig import EinJahrFreiwillig as scr
>>> i = scr('test')
>>> i.add_urls()
>>> i.crawl(i.urls[0], 1)
>>> i.data
```
> 216 Added crawler for ein-jahr-freiwillig.de

- app/src/views/About.vue
- etl/data_enhancement/enhance_data.py
- etl/data_extraction/Scraper.py
- etl/data_extraction/scrape_data.py
- etl/data_extraction/scraper/bundesfreiwilligendienst.py
Crawler implementation for bundesfreiwilligendienst.de
Can be tested with the following commands:
```
$ cd etl
$ python (or python3)
>>> from shared.utils import write_data_to_json
>>> write_data_to_json('data_extraction/data/test.json', [])
>>> from data_extraction.scraper.bundesfreiwilligendienst import BundesFreiwilligendienst as scr
>>> i = scr('test')
>>> i.add_urls()
>>> import random
>>> for j in range(0, 20):
...    i.crawl(i.urls[j], random.randrange(len(i.urls)))
```
> 237/add crawler for bundesfreiwilligendienst.de

- etl/test/test_data_enhancement/enhancement_duplicates/test_enhancement_exact_duplicates.py
- etl/test/test_data_enhancement/enhancement_location/test_lat_lon_enhancer.py
- etl/test/test_data_extraction/test_Scraper.py
Closes #255. 
The problem was that the directories in the test directory had the same name as the real directories. Also the ROOT_DIR was missing in the tests.
Can be tested with the following commands:
```
$ cd (einander-helfen)/etl
$ pip3 install -r requirements.txt
$ python3 -m unittest
```
> Fixed python unit tests

- etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
In order to add more accurate coordinates to the posts, a further function has been added to the enhancement process to use the unstructured location data first before referencing the land.
In addition, unsuccessful geocoder requests are stored in a blacklist to speed up future requests.
close #290
> 290/revise address parsing for unstructured address fields 

- app/src/components/layout/Toolbar.vue
Change deprecated v-toolbar-side-icon to v-app-bar-nav-icon.
See [vuetify changelog](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0-beta.0) and search for `v-toolbar-side-icon`
closes #309
> Use v-app-bar-nav-icon

- app/src/components/posts/PostCard.vue
fixe the details view title. E.g. search "Internationale Strolche" in "Köln"
close 287
> #287/display title correctly

- app/src/components/posts/PostCard.vue
When selecting a post, the detail view shows now the beginning of the offer.
close #236
> #236 fix scrolled down post detail view

- etl/scripts/run_etl.sh
- etl/upload_to_elasticsearch/elastic.py
Refactored the elasticsearch upload:
1. Create temporary index (`posts_tmp`)
2. write new Data to the temporary index
3. Reinitialize main index (`posts`)
4. Reindex `posts_tmp` index with `posts` as destination
5. Delete `posts_tmp`
> #271/use second index for elasticsearch upload

- app/src/components/posts/MapCard.vue
This is achieved by disabling the gestureHandling on Desktop.
closes #275
> Make map scrollable without ctrl on desktop

- app/src/components/posts/MapCard.vue
Use [german osm data](https://www.openstreetmap.de/germanstyle.html), so in nations that have no latin-letters, they will have an alternative name displayed.
closes #325
> Use german osm data

- .gitignore
- etl/scripts/run_etl.sh
Revised the `/etl/scripts/run_etel.sh` script to create a lockfile called `ETLlock` which prevents parallel execution of the script.
Closes #423
> #423 Avoidance of multiple parallel etl processes

- app/src/store/store.ts
Sets the "page" query to undefined for page 1 so it won't show up in the url.
closes #457
> Remove pagination query from url for page 1

- .gitignore
- etl/.devcontainer/Dockerfile
- etl/.devcontainer/devcontainer.json
This PR adds the files needed to run our backend app inside of a devcontainer. This one is much simpler than the FE one.
The container runs in Debian 11 using the current latest Python3 version (v3.10). Both are fixed.
For performance optimization, the pip dependencies are cached as a part of the base image. This might need to be changed if we expect them to change more often.
The container also includes the basic python extensions for VSCode.
> Add backend devcontainer

- app/public/index.html
Reason (Why?)
Crawler does not recognize links because of missing meta tags.
Solution (What?)
Add an meta description to each page to test the impact on SEO checkers.
> #459 add meta fragment for better crawling 

- etl/.devcontainer/devcontainer.json
Disabled linting in devcontainer because it had too many issues and solving them would not be worth the time.
> Disable linting in be devcontainer settings

- app/src/components/layout/Carousel.vue
The images inside the carousel component were still dragable, which lead to issues with the component. This has been removed.
Also the cursor was changed to pointer to suggest interaction by the user.
> landing page image carousel fix

- app/src/components/layout/SearchHeader.vue
- app/src/components/posts/MapCard.vue
- app/src/views/Posts.vue
When clicking on the text of a pin, scroll to the detail description of the post.
There is 1 Issue that needs to be discussed:
The issue stated, that the post should only be opened by clicking  a second time on the pin (or more specific clicking on the text of the pin). The click event will be captured by the map itself rather that the pin text which results in closing the pin text before the click-handler of the pin text can fire. So the feature does only work if we always show the pin text rather than only showing it after tapping the pin.
As far as i found out it is not possible to dynamically toggle the text to keep open for the current selected post.
So we have 3 options:
1.  Close this issue as not possible
2. always keep the pin text open on mobile
3. scroll to the post description …
> Open detailed post by clicking on a pin on mobile

- app/public/robots.txt
This PR simply adds a robots.txt which allows all crawlers, but blocks them from indexing /posts
> Add robots.txt blocking /posts urls

- app/package.json
- app/src/main.ts
- app/src/views/About.vue
- app/src/views/Home.vue
- app/src/views/Imprint.vue
- app/src/views/Organizations.vue
- app/src/views/PageNotFound.vue
- app/src/views/Posts.vue
- app/src/views/Privacy.vue
- app/yarn.lock
Adds canonical tags to all views (without our non-indexed posts).
This is achieved using [vue-meta](https://vue-meta.nuxtjs.org/) which seems to be the standard for managing meta tags for seo.
As vue-meta  also manage the document titles, I refactored our code so we use vue-meta for this also.
closes #511
and duplicate issue:
closes #456
> Add canoncial tags with help from vue-meta
